#Music : https://musiclab.chromeexperiments.com/Song-Maker/song/5468509057974272
print()
print("         Welcome To The First Game I Ever Coded!")
print()
print("                  PowerPlay Presents")
print()
print("         Origin: A Text Adventure")
print()
print("Now, What Shall Your Avatar's Name Be?")
player1 = input()
print(f"     {player1}, Is A Very Interesting Name")
print()
print(f"Well {player1}, Your Quest Begins Now...")
print()
print(" It Had Just Turned 7:30 P.M When Someone Came Knocking At Your Door...")
print("What Do You Do?")

doorOpened = False
while not doorOpened:
    door = input()
    print()
    if door.lower() == "open door" or door.lower() == "open" or door.lower() == "open the door" or door.lower() == "answer the door" or door.lower() == "answer door" or door.lower() == "answer it" or door.lower() == "answer":
        print("You See Your Friend")
        print()
        print("     ???: Come On, Hurry Up")
        doorOpened = True
    else:
        print("The Knocking Becomes Louder!")
print()
print("    It's Your Friend,")
print("But What Was His Name?")
print()
print("Friend's Name:")
player2 = input()
print()
print(f"    {player2}: Come on, We're Going To Be Late")
print()
print("As You Hurry Down The Stone Pathway, You Notice That The Sun Is Already Setting, You Haden't Noticed That It Got So Late")
print()
print(f"     {player2}: So, Are You Ready?")
print()
print(" What Do You Say?")
print()
print("Yes -OR- Not Really")
ready1 = input()
if ready1.lower() == "yes" or ready1.lower() == "yes!" or ready1.lower() == "yeah" or ready1.lower() == "yeah!":
    print(f"    {player2}: Great!")
else:
    print(f"    {player2}: I'm Kinda Nervous Too")
print()
print("You Could Tell He Was One Problem Away From Pulling His Hair Out")
print(" But, To Be Fair, Leaving Your Village Was A Big Deal")
print()
print(      "Once Someone Hits 12 Years Old, They Have A Chance To Leave The Village And Start Their Own Life")
print(f"  {player2} Is A Year Younger Then You Though")
print()
print(f"    You Were Sad To Leave The Village, But You Were Sure That In A Year, {player2} Would Catch Up To You")
print()
print(f"    {player2}: Come On! You Don't Wanna Be Late For Your Own Party!")
print(f"You And {player2} Start To Jog To Your Party")
print()
print()
print("When You Get There, You See All Your Family, Friends, And Everyone In The Village There")
print()
print("     ???: He's Here! Speech! Speech! Speech!")
print()
print(" The Crowd Starts To Chant")
print()
print("         Do You Give A Speech?")
print()
print("     Yes -OR- No")
speech = input()
if speech.lower() == "yes!" or speech.lower() == "yes" or speech.lower() == "yeah" or speech.lower() == "yeah!":
    print("    CROWD: Yay!")
    print()
    print("Well, I'm Leaving, And I Hope To Find My Own Way Outside Of This Village. Mabye If Some Of You Choose To, When You Come Of Age, You'll Leave The Village, And I Might Run Into You.")
    print("   If Not, I Hope That All Of You Thrive In Life.")
    print()
    print("The Crowd Starts Cheering")
else:
    print("    CROWD: Aww...")
print()
print("     YOU: But Let The Party Begin!")
print()
#Music: https://musiclab.chromeexperiments.com/Song-Maker/song/4609637804015616
print()
print("     The Party Was Done A Half-Hour Ago And Now You Were Putting The Final Thing In Your Backpack")
print("   You Start Down The Path That Leads Out Of The Village, But Stop. You Turn Around And Take One Last Look At The Place You Grew Up. Then, You Leave The Village.")
#Music: https://musiclab.chromeexperiments.com/Song-Maker/song/5788314268991488
print()
print("     Not Long After You Leave, You Hear Footsteps Behind You.")
print(f" You Spin And See {player2}")
print()
print(f"{player2}: Calm Down, It's Just Me")
print("     YOU: Why Are You Here?")
print()
print(f"    {player2}: ...")
print(f"    {player2}: I'm Coming With You.")
print(" You Grin")
print("     YOU: I Would Love The Company")
print()
print("You And Him Start Walking Farther And Farther Away From The Village, Talking About What You Think Will Happen")